<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SAGE.Domain\SAGE.Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="8.4.0" />
		<PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.11.0" />
		<PackageReference Include="FluentMigrator" Version="7.1.0" />
		<PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4" />
		<PackageReference Include="Npgsql" Version="9.0.3" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>


	<PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
